### ISSUE TITLE
Follow dependency chain, install bottom first

### ISSUE THREAD

**Issue by maphew** [maphew/apt#17]
also: http://trac.osgeo.org/osgeo4w/ticket/283

```
D:\osgeo>apt install shell
to install:    setup shell msvcrt

...downloads happen...

Traceback (most recent call last):
  File "<string>", line 1524, in <module>
  File "<string>", line 299, in install
  File "<string>", line 316, in install_next
  File "<string>", line 315, in install_next
Exception: Required package setup from shell is a circular reference with a prev
ious dependent

D:\osgeo>apt requires shell msvcrt setup
----- "shell" requires the following to work -----
msvcrt
setup
----- "msvcrt" requires the following to work -----

----- "setup" requires the following to work -----
msvcrt
shell

D:\osgeo>apt --no-deps install shell
to install:    shell
...
installing shell 1.0.0-13

D:\osgeo\Osgeo4w-apt>mkdir "C:\ProgramData\Microsoft\Windows\Start Menu\Programs
\OSGeo4W"
Access is denied.

D:\osgeo\Osgeo4w-apt>xxmklink "C:\ProgramData\Microsoft\Windows\Start Menu\Progr
ams\OSGeo4W\OSGeo4W.lnk" "D:\osgeo\Osgeo4w-apt\OSGeo4W.bat" " " \ "OSGeo for Win
dows command shell" 1 "D:\osgeo\Osgeo4w-apt\OSGeo4W.ico"
'xxmklink' is not recognized as an internal or external command,
operable program or batch file.
...
Post_install complete, return code 1
```

**Comment by maphew** [comment]
Implementation is partway there: as of close of #21, install logic installs dependencies before the named package, but groups all dependencies together. So with the chain `iconv <- shell <- setup, msvcrt`, *shell, setup* & *msvcrt* are all installed first, but shell still tries to install before it's dependencies, *setup* & *msvcrt*.
