### ISSUE TITLE
AttributeError: module 'ctypes' has no attribute 'util'

### ISSUE THREAD

**Issue by hend019** [maphew/apt#56]
I Tried running python program to controlling thorlabs motor controller. I found error codes such below:
Traceback (most recent call last):
  File "C:\Users\N 417 TA\Desktop\meanshift.py", line 6, in <module>
    import thorlabs_apt as apt
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\__init__.py", line 1, in <module>
    from .core import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\core.py", line 1373, in <module>
    _lib = _load_library()
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\core.py", line 1354, in _load_library
    filename = ctypes.util.find_library("APT")
AttributeError: module 'ctypes' has no attribute 'util'
As information, I using python 3.6.0 64 bit.

**Comment by maphew** [comment]
Different `apt`. I think you meant to file this at https://github.com/qpit/thorlabs_apt @hend019  ;-)

**Comment by hend019** [comment]
@maphew Thanks for your information. After I tried I found other error from the thorlabs library. 
The error such this:
File "C:\Users\N 417 TA\Desktop\meanshift.py", line 6, in <module>
    import thorlabs_apt as apt
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\__init__.py", line 1, in <module>
    from .core import *
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\core.py", line 1376, in <module>
    _lib = _load_library()
  File "C:\ProgramData\Anaconda3\lib\site-packages\thorlabs_apt-0.1-py3.6.egg\thorlabs_apt\core.py", line 1370, in _load_library
    "%s" % _get_error_text(err_code))
Exception: Thorlabs APT Initialization failed: COM system error

Do you have information about it?

**Comment by maphew** [comment]
Sorry no, I don't have information on it.
